DOCUMENT := how-to-select-fonts

default:
	@pdflatex $(DOCUMENT)

clean:
	@rm -f how-to-select-fonts.aux
	@rm -f how-to-select-fonts.log
	@rm -f how-to-select-fonts.out
	@rm -f how-to-select-fonts.toc
