DEMOFILE := demo
CICUTA   := cicuta

default:
	@pdflatex $(DEMOFILE)

clean:
	@rm -f $(DEMOFILE).log
	@rm -f $(DEMOFILE).aux
	@rm -f $(DEMOFILE).pdf
	@rm -f $(DEMOFILE).out
	@rm -f $(DEMOFILE).tex
	@rm -f $(CICUTA).log
	@rm -f $(CICUTA).aux
	@rm -f $(CICUTA).pdf
	@rm -f $(CICUTA).out
	@rm -f 'cicuta.lyx~'
